-- Product registration, inventory detail, and auditable stock movements.

create table public.inventory_movements (
  id bigint generated by default as identity primary key,
  product_id uuid not null references public.products (id) on delete cascade,
  movement_type text not null
    check (movement_type in ('initial', 'inbound', 'outbound', 'adjustment')),
  quantity_delta integer not null check (quantity_delta <> 0),
  previous_on_hand integer not null check (previous_on_hand >= 0),
  resulting_on_hand integer not null check (resulting_on_hand >= 0),
  reason text not null check (length(trim(reason)) > 0),
  created_by uuid references auth.users (id) on delete set null,
  created_at timestamptz not null default now()
);

create index inventory_movements_product_created_idx
on public.inventory_movements (product_id, created_at desc);

alter table public.inventory_movements enable row level security;

create policy "inventory_movements_admin_all"
on public.inventory_movements for all to authenticated
using ((select public.is_admin()))
with check ((select public.is_admin()));

grant select, insert on public.inventory_movements to authenticated;
grant usage, select on sequence public.inventory_movements_id_seq to authenticated;

insert into public.inventory_movements (
  product_id,
  movement_type,
  quantity_delta,
  previous_on_hand,
  resulting_on_hand,
  reason
)
select
  inventory.product_id,
  'initial',
  inventory.on_hand,
  0,
  inventory.on_hand,
  '기존 재고 이관'
from public.inventory
where inventory.on_hand > 0;

create function public.get_inventory_detail(p_product_id uuid)
returns jsonb
language sql
stable
security invoker
set search_path = ''
as $$
  select jsonb_build_object(
    'productId', products.id,
    'sku', products.sku,
    'name', products.name,
    'description', products.description,
    'price', products.price,
    'productStatus', products.status,
    'onHand', inventory.on_hand,
    'reserved', inventory.reserved,
    'available', inventory.available,
    'reorderPoint', inventory.reorder_point,
    'stockStatus', case
      when inventory.available <= 0 then 'sold_out'
      when inventory.available <= inventory.reorder_point then 'low_stock'
      else 'normal'
    end,
    'updatedAt', greatest(products.updated_at, inventory.updated_at),
    'movements', coalesce(
      (
        select jsonb_agg(
          jsonb_build_object(
            'id', movements.id,
            'movementType', movements.movement_type,
            'quantityDelta', movements.quantity_delta,
            'previousOnHand', movements.previous_on_hand,
            'resultingOnHand', movements.resulting_on_hand,
            'reason', movements.reason,
            'createdBy', profiles.display_name,
            'createdAt', movements.created_at
          )
          order by movements.created_at desc, movements.id desc
        )
        from (
          select inventory_movements.*
          from public.inventory_movements
          where inventory_movements.product_id = products.id
          order by inventory_movements.created_at desc, inventory_movements.id desc
          limit 30
        ) as movements
        left join public.profiles on profiles.id = movements.created_by
      ),
      '[]'::jsonb
    )
  )
  from public.products
  join public.inventory on inventory.product_id = products.id
  where products.id = p_product_id;
$$;

create function public.create_inventory_product(p_payload jsonb)
returns jsonb
language plpgsql
security invoker
set search_path = ''
as $$
declare
  created_product_id uuid;
  next_sku text;
  next_name text;
  next_description text;
  next_price integer;
  next_product_status text;
  next_on_hand integer;
  next_reorder_point integer;
  invalid_key text;
begin
  if p_payload is null or jsonb_typeof(p_payload) <> 'object' then
    raise exception '등록할 상품 정보를 확인해 주세요.' using errcode = '22023';
  end if;

  select keys.key
  into invalid_key
  from jsonb_object_keys(p_payload) as keys(key)
  where keys.key not in (
    'sku',
    'name',
    'description',
    'price',
    'productStatus',
    'onHand',
    'reorderPoint'
  )
  limit 1;

  if invalid_key is not null then
    raise exception '등록할 수 없는 상품 필드입니다: %', invalid_key
      using errcode = '22023';
  end if;

  next_sku := upper(trim(coalesce(p_payload ->> 'sku', '')));
  next_name := trim(coalesce(p_payload ->> 'name', ''));
  next_description := nullif(trim(coalesce(p_payload ->> 'description', '')), '');
  next_price := coalesce((p_payload ->> 'price')::integer, 0);
  next_product_status := coalesce(p_payload ->> 'productStatus', 'active');
  next_on_hand := coalesce((p_payload ->> 'onHand')::integer, 0);
  next_reorder_point := coalesce((p_payload ->> 'reorderPoint')::integer, 10);

  if next_sku = '' or next_name = '' then
    raise exception 'SKU와 상품명을 입력해 주세요.' using errcode = '22023';
  end if;

  if next_price < 0 or next_on_hand < 0 or next_reorder_point < 0 then
    raise exception '가격과 재고 수량은 0 이상이어야 합니다.' using errcode = '22023';
  end if;

  if next_product_status not in ('active', 'inactive') then
    raise exception '상품 상태를 확인해 주세요.' using errcode = '22023';
  end if;

  if exists (
    select 1 from public.products where products.sku = next_sku
  ) then
    raise exception '이미 사용 중인 SKU입니다.' using errcode = '23505';
  end if;

  insert into public.products (sku, name, description, price, status)
  values (
    next_sku,
    next_name,
    next_description,
    next_price,
    next_product_status
  )
  returning id into created_product_id;

  insert into public.inventory (product_id, on_hand, reserved, reorder_point)
  values (created_product_id, next_on_hand, 0, next_reorder_point);

  if next_on_hand > 0 then
    insert into public.inventory_movements (
      product_id,
      movement_type,
      quantity_delta,
      previous_on_hand,
      resulting_on_hand,
      reason,
      created_by
    )
    values (
      created_product_id,
      'initial',
      next_on_hand,
      0,
      next_on_hand,
      '상품 등록 시 최초 재고',
      (select auth.uid())
    );
  end if;

  return public.get_inventory_detail(created_product_id);
end;
$$;

create function public.update_inventory_product(
  p_product_id uuid,
  p_payload jsonb
)
returns jsonb
language plpgsql
security invoker
set search_path = ''
as $$
declare
  current_product public.products%rowtype;
  current_inventory public.inventory%rowtype;
  next_name text;
  next_description text;
  next_price integer;
  next_product_status text;
  next_reorder_point integer;
  invalid_key text;
begin
  if p_payload is null or jsonb_typeof(p_payload) <> 'object' then
    raise exception '수정할 상품 정보를 확인해 주세요.' using errcode = '22023';
  end if;

  select keys.key
  into invalid_key
  from jsonb_object_keys(p_payload) as keys(key)
  where keys.key not in (
    'name',
    'description',
    'price',
    'productStatus',
    'reorderPoint'
  )
  limit 1;

  if invalid_key is not null then
    raise exception '수정할 수 없는 상품 필드입니다: %', invalid_key
      using errcode = '22023';
  end if;

  select products.*
  into current_product
  from public.products
  where products.id = p_product_id
  for update;

  select inventory.*
  into current_inventory
  from public.inventory
  where inventory.product_id = p_product_id
  for update;

  if current_product.id is null or current_inventory.product_id is null then
    raise exception '재고 상품을 찾을 수 없습니다.' using errcode = 'P0002';
  end if;

  next_name := case
    when p_payload ? 'name' then trim(coalesce(p_payload ->> 'name', ''))
    else current_product.name
  end;
  next_description := case
    when p_payload ? 'description'
      then nullif(trim(coalesce(p_payload ->> 'description', '')), '')
    else current_product.description
  end;
  next_price := case
    when p_payload ? 'price' then (p_payload ->> 'price')::integer
    else current_product.price
  end;
  next_product_status := case
    when p_payload ? 'productStatus' then p_payload ->> 'productStatus'
    else current_product.status
  end;
  next_reorder_point := case
    when p_payload ? 'reorderPoint' then (p_payload ->> 'reorderPoint')::integer
    else current_inventory.reorder_point
  end;

  if next_name = '' then
    raise exception '상품명을 입력해 주세요.' using errcode = '22023';
  end if;

  if next_price < 0 or next_reorder_point < 0 then
    raise exception '가격과 안전 재고는 0 이상이어야 합니다.' using errcode = '22023';
  end if;

  if next_product_status not in ('active', 'inactive') then
    raise exception '상품 상태를 확인해 주세요.' using errcode = '22023';
  end if;

  update public.products
  set
    name = next_name,
    description = next_description,
    price = next_price,
    status = next_product_status
  where id = p_product_id;

  update public.inventory
  set reorder_point = next_reorder_point
  where product_id = p_product_id;

  return public.get_inventory_detail(p_product_id);
end;
$$;

create function public.adjust_inventory_stock(
  p_product_id uuid,
  p_payload jsonb
)
returns jsonb
language plpgsql
security invoker
set search_path = ''
as $$
declare
  current_inventory public.inventory%rowtype;
  next_movement_type text;
  input_quantity integer;
  quantity_delta integer;
  next_on_hand integer;
  next_reason text;
  invalid_key text;
begin
  if p_payload is null or jsonb_typeof(p_payload) <> 'object' then
    raise exception '재고 조정 정보를 확인해 주세요.' using errcode = '22023';
  end if;

  select keys.key
  into invalid_key
  from jsonb_object_keys(p_payload) as keys(key)
  where keys.key not in ('movementType', 'quantity', 'reason')
  limit 1;

  if invalid_key is not null then
    raise exception '처리할 수 없는 재고 조정 필드입니다: %', invalid_key
      using errcode = '22023';
  end if;

  next_movement_type := p_payload ->> 'movementType';
  input_quantity := (p_payload ->> 'quantity')::integer;
  next_reason := trim(coalesce(p_payload ->> 'reason', ''));

  if next_movement_type not in ('inbound', 'outbound', 'adjustment') then
    raise exception '재고 조정 유형을 확인해 주세요.' using errcode = '22023';
  end if;

  if input_quantity is null or input_quantity < 0 then
    raise exception '재고 수량은 0 이상이어야 합니다.' using errcode = '22023';
  end if;

  if next_movement_type in ('inbound', 'outbound') and input_quantity = 0 then
    raise exception '입출고 수량은 1개 이상이어야 합니다.' using errcode = '22023';
  end if;

  if next_reason = '' then
    raise exception '재고 변경 사유를 입력해 주세요.' using errcode = '22023';
  end if;

  select inventory.*
  into current_inventory
  from public.inventory
  where inventory.product_id = p_product_id
  for update;

  if not found then
    raise exception '재고 정보를 찾을 수 없습니다.' using errcode = 'P0002';
  end if;

  next_on_hand := case next_movement_type
    when 'inbound' then current_inventory.on_hand + input_quantity
    when 'outbound' then current_inventory.on_hand - input_quantity
    else input_quantity
  end;
  quantity_delta := next_on_hand - current_inventory.on_hand;

  if next_on_hand < current_inventory.reserved then
    raise exception '변경 후 보유 재고는 예약 재고보다 적을 수 없습니다.'
      using errcode = '22023';
  end if;

  if quantity_delta = 0 then
    raise exception '현재 재고와 다른 수량을 입력해 주세요.' using errcode = '22023';
  end if;

  update public.inventory
  set on_hand = next_on_hand
  where product_id = p_product_id;

  insert into public.inventory_movements (
    product_id,
    movement_type,
    quantity_delta,
    previous_on_hand,
    resulting_on_hand,
    reason,
    created_by
  )
  values (
    p_product_id,
    next_movement_type,
    quantity_delta,
    current_inventory.on_hand,
    next_on_hand,
    next_reason,
    (select auth.uid())
  );

  return public.get_inventory_detail(p_product_id);
end;
$$;

drop function public.update_inventory(uuid, jsonb);

revoke all on function public.get_inventory_detail(uuid) from public;
grant execute on function public.get_inventory_detail(uuid) to authenticated;

revoke all on function public.create_inventory_product(jsonb) from public;
grant execute on function public.create_inventory_product(jsonb) to authenticated;

revoke all on function public.update_inventory_product(uuid, jsonb) from public;
grant execute on function public.update_inventory_product(uuid, jsonb) to authenticated;

revoke all on function public.adjust_inventory_stock(uuid, jsonb) from public;
grant execute on function public.adjust_inventory_stock(uuid, jsonb) to authenticated;

comment on function public.get_inventory_detail(uuid) is
  'Returns product information, current inventory, and recent stock movements.';
comment on function public.create_inventory_product(jsonb) is
  'Creates a product and its initial inventory in one transaction.';
comment on function public.update_inventory_product(uuid, jsonb) is
  'Updates editable product information and the reorder point.';
comment on function public.adjust_inventory_stock(uuid, jsonb) is
  'Applies an inbound, outbound, or stocktake adjustment and records its history.';
