-- Editable order detail fields, status audit history, and consultation notes.

alter table public.order_status_history
add column changed_by uuid references auth.users (id) on delete set null;

create table public.order_consultation_notes (
  id bigint generated by default as identity primary key,
  order_id uuid not null references public.orders (id) on delete cascade,
  author_id uuid references auth.users (id) on delete set null,
  content text not null check (char_length(trim(content)) between 1 and 2000),
  created_at timestamptz not null default now()
);

create index order_consultation_notes_order_created_idx
on public.order_consultation_notes (order_id, created_at desc);

alter table public.order_consultation_notes enable row level security;

create policy "order_consultation_notes_admin_select"
on public.order_consultation_notes for select to authenticated
using ((select public.is_admin()));

create policy "order_consultation_notes_admin_insert"
on public.order_consultation_notes for insert to authenticated
with check (
  (select public.is_admin())
  and author_id = (select auth.uid())
);

grant select, insert on public.order_consultation_notes to authenticated;
grant usage, select on sequence public.order_consultation_notes_id_seq
to authenticated, service_role;

with demo_notes(order_number, content, created_offset) as (
  values
    ('FO-DEMO-0182', '고객 요청으로 선물 포장 상태를 확인했습니다.', interval '20 minutes'),
    ('FO-DEMO-0182', '출고 전 배송지 변경 가능 여부를 안내했습니다.', interval '10 minutes'),
    ('FO-DEMO-0177', '상품 준비 일정과 예상 출고일을 안내했습니다.', interval '40 minutes'),
    ('FO-DEMO-0176', '운송장 번호와 배송 조회 방법을 전달했습니다.', interval '1 hour')
)
insert into public.order_consultation_notes (
  order_id,
  author_id,
  content,
  created_at
)
select
  orders.id,
  (select profiles.id from public.profiles where profiles.role = 'admin' limit 1),
  demo_notes.content,
  now() - demo_notes.created_offset
from demo_notes
join public.orders on orders.order_number = demo_notes.order_number;

create function public.handle_order_status_change()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  if old.status is distinct from new.status then
    insert into public.order_status_history (
      order_id,
      status,
      changed_by,
      note,
      changed_at
    )
    values (
      new.id,
      new.status,
      (select auth.uid()),
      case new.status
        when 'paid' then '결제가 완료되었습니다.'
        when 'preparing' then '상품 준비가 시작되었습니다.'
        when 'shipping' then '배송이 시작되었습니다.'
        when 'delivered' then '배송이 완료되었습니다.'
        when 'cancelled' then '주문이 취소되었습니다.'
      end,
      now()
    );
  end if;

  return new;
end;
$$;

create function public.update_order_detail(
  p_order_id uuid,
  p_payload jsonb
)
returns jsonb
language plpgsql
security invoker
set search_path = ''
as $$
declare
  current_status text;
  next_status text;
  invalid_key text;
begin
  if p_payload is null or jsonb_typeof(p_payload) <> 'object' then
    raise exception '수정할 주문 정보를 확인해 주세요.' using errcode = '22023';
  end if;

  select orders.status
  into current_status
  from public.orders
  where orders.id = p_order_id
  for update;

  if not found then
    raise exception '주문을 찾을 수 없습니다.' using errcode = 'P0002';
  end if;

  select keys.key
  into invalid_key
  from jsonb_object_keys(p_payload) as keys(key)
  where keys.key not in (
    'status',
    'customerName',
    'customerEmail',
    'customerPhone',
    'recipientName',
    'recipientPhone',
    'postalCode',
    'addressLine1',
    'addressLine2',
    'deliveryMemo',
    'carrier',
    'trackingNumber'
  )
  limit 1;

  if invalid_key is not null then
    raise exception '수정할 수 없는 주문 필드입니다: %', invalid_key
      using errcode = '22023';
  end if;

  if p_payload ?| array['customerName', 'customerEmail', 'customerPhone']
    and current_status not in ('paid', 'preparing') then
    raise exception '현재 주문 상태에서는 고객 정보를 수정할 수 없습니다.'
      using errcode = '22023';
  end if;

  if p_payload ?| array[
    'recipientName',
    'recipientPhone',
    'postalCode',
    'addressLine1',
    'addressLine2',
    'deliveryMemo'
  ] and current_status not in ('paid', 'preparing') then
    raise exception '현재 주문 상태에서는 배송지 정보를 수정할 수 없습니다.'
      using errcode = '22023';
  end if;

  if p_payload ?| array['carrier', 'trackingNumber']
    and current_status not in ('preparing', 'shipping') then
    raise exception '현재 주문 상태에서는 배송 정보를 수정할 수 없습니다.'
      using errcode = '22023';
  end if;

  if p_payload ? 'customerName'
    and nullif(trim(p_payload ->> 'customerName'), '') is null then
    raise exception '주문자 이름은 비워둘 수 없습니다.' using errcode = '22023';
  end if;

  if p_payload ? 'recipientName'
    and nullif(trim(p_payload ->> 'recipientName'), '') is null then
    raise exception '수령인 이름은 비워둘 수 없습니다.' using errcode = '22023';
  end if;

  if p_payload ? 'recipientPhone'
    and nullif(trim(p_payload ->> 'recipientPhone'), '') is null then
    raise exception '수령인 연락처는 비워둘 수 없습니다.' using errcode = '22023';
  end if;

  if p_payload ? 'postalCode'
    and nullif(trim(p_payload ->> 'postalCode'), '') is null then
    raise exception '우편번호는 비워둘 수 없습니다.' using errcode = '22023';
  end if;

  if p_payload ? 'addressLine1'
    and nullif(trim(p_payload ->> 'addressLine1'), '') is null then
    raise exception '기본 주소는 비워둘 수 없습니다.' using errcode = '22023';
  end if;

  if p_payload ? 'status' then
    next_status := nullif(trim(p_payload ->> 'status'), '');

    if next_status is null then
      raise exception '변경할 주문 상태를 확인해 주세요.' using errcode = '22023';
    end if;

    if next_status <> current_status and not (
      (current_status = 'paid' and next_status in ('preparing', 'cancelled'))
      or (current_status = 'preparing' and next_status in ('shipping', 'cancelled'))
      or (current_status = 'shipping' and next_status = 'delivered')
    ) then
      raise exception '현재 주문 상태에서 요청한 상태로 변경할 수 없습니다.'
        using errcode = '22023';
    end if;
  end if;

  update public.orders
  set
    customer_name = case
      when p_payload ? 'customerName' then trim(p_payload ->> 'customerName')
      else customer_name
    end,
    customer_email = case
      when p_payload ? 'customerEmail' then nullif(trim(p_payload ->> 'customerEmail'), '')
      else customer_email
    end,
    customer_phone = case
      when p_payload ? 'customerPhone' then nullif(trim(p_payload ->> 'customerPhone'), '')
      else customer_phone
    end,
    status = case
      when p_payload ? 'status' then next_status
      else status
    end
  where id = p_order_id;

  if p_payload ?| array[
    'recipientName',
    'recipientPhone',
    'postalCode',
    'addressLine1',
    'addressLine2',
    'deliveryMemo',
    'carrier',
    'trackingNumber'
  ] then
    update public.order_shipments
    set
      recipient_name = case
        when p_payload ? 'recipientName' then trim(p_payload ->> 'recipientName')
        else recipient_name
      end,
      recipient_phone = case
        when p_payload ? 'recipientPhone' then trim(p_payload ->> 'recipientPhone')
        else recipient_phone
      end,
      postal_code = case
        when p_payload ? 'postalCode' then trim(p_payload ->> 'postalCode')
        else postal_code
      end,
      address_line1 = case
        when p_payload ? 'addressLine1' then trim(p_payload ->> 'addressLine1')
        else address_line1
      end,
      address_line2 = case
        when p_payload ? 'addressLine2' then nullif(trim(p_payload ->> 'addressLine2'), '')
        else address_line2
      end,
      delivery_memo = case
        when p_payload ? 'deliveryMemo' then nullif(trim(p_payload ->> 'deliveryMemo'), '')
        else delivery_memo
      end,
      carrier = case
        when p_payload ? 'carrier' then nullif(trim(p_payload ->> 'carrier'), '')
        else carrier
      end,
      tracking_number = case
        when p_payload ? 'trackingNumber' then nullif(trim(p_payload ->> 'trackingNumber'), '')
        else tracking_number
      end
    where order_id = p_order_id;

    if not found then
      raise exception '배송 정보를 찾을 수 없습니다.' using errcode = 'P0002';
    end if;
  end if;

  return public.get_order_detail(p_order_id);
end;
$$;

create trigger orders_add_status_history
after update of status on public.orders
for each row execute function public.handle_order_status_change();

create or replace function public.get_order_detail(p_order_id uuid)
returns jsonb
language sql
stable
security invoker
set search_path = ''
as $$
  select jsonb_build_object(
    'id', orders.id,
    'orderNumber', orders.order_number,
    'status', orders.status,
    'orderedAt', orders.ordered_at,
    'updatedAt', orders.updated_at,
    'totalAmount', orders.total_amount,
    'salesChannel', sales_channels.name,
    'editableFields', case orders.status
      when 'paid' then jsonb_build_array('customer', 'shipping', 'status')
      when 'preparing' then jsonb_build_array('customer', 'shipping', 'tracking', 'status')
      when 'shipping' then jsonb_build_array('tracking', 'status')
      else '[]'::jsonb
    end,
    'availableStatuses', case orders.status
      when 'paid' then jsonb_build_array('preparing', 'cancelled')
      when 'preparing' then jsonb_build_array('shipping', 'cancelled')
      when 'shipping' then jsonb_build_array('delivered')
      else '[]'::jsonb
    end,
    'customer', jsonb_build_object(
      'name', orders.customer_name,
      'email', orders.customer_email,
      'phone', orders.customer_phone
    ),
    'items', (
      select coalesce(
        jsonb_agg(
          jsonb_build_object(
            'id', order_items.id,
            'productId', order_items.product_id,
            'sku', order_items.product_sku,
            'name', order_items.product_name,
            'quantity', order_items.quantity,
            'unitPrice', order_items.unit_price,
            'totalAmount', order_items.unit_price * order_items.quantity
          )
          order by order_items.id
        ),
        '[]'::jsonb
      )
      from public.order_items
      where order_items.order_id = orders.id
    ),
    'payment', (
      select jsonb_build_object(
        'method', order_payments.method,
        'status', order_payments.status,
        'productAmount', order_payments.product_amount,
        'discountAmount', order_payments.discount_amount,
        'shippingFee', order_payments.shipping_fee,
        'paidAmount', order_payments.paid_amount,
        'transactionId', order_payments.transaction_id,
        'paidAt', order_payments.paid_at,
        'refundedAt', order_payments.refunded_at
      )
      from public.order_payments
      where order_payments.order_id = orders.id
    ),
    'shipping', (
      select jsonb_build_object(
        'recipientName', order_shipments.recipient_name,
        'recipientPhone', order_shipments.recipient_phone,
        'postalCode', order_shipments.postal_code,
        'addressLine1', order_shipments.address_line1,
        'addressLine2', order_shipments.address_line2,
        'deliveryMemo', order_shipments.delivery_memo,
        'carrier', order_shipments.carrier,
        'trackingNumber', order_shipments.tracking_number,
        'shippedAt', order_shipments.shipped_at,
        'deliveredAt', order_shipments.delivered_at
      )
      from public.order_shipments
      where order_shipments.order_id = orders.id
    ),
    'statusHistory', (
      select coalesce(
        jsonb_agg(
          jsonb_build_object(
            'id', order_status_history.id,
            'status', order_status_history.status,
            'note', order_status_history.note,
            'changedAt', order_status_history.changed_at,
            'changedBy', profiles.display_name
          )
          order by order_status_history.changed_at desc
        ),
        '[]'::jsonb
      )
      from public.order_status_history
      left join public.profiles on profiles.id = order_status_history.changed_by
      where order_status_history.order_id = orders.id
    ),
    'consultationNotes', (
      select coalesce(
        jsonb_agg(
          jsonb_build_object(
            'id', order_consultation_notes.id,
            'content', order_consultation_notes.content,
            'authorId', order_consultation_notes.author_id,
            'authorName', profiles.display_name,
            'createdAt', order_consultation_notes.created_at
          )
          order by order_consultation_notes.created_at desc
        ),
        '[]'::jsonb
      )
      from public.order_consultation_notes
      left join public.profiles on profiles.id = order_consultation_notes.author_id
      where order_consultation_notes.order_id = orders.id
    )
  )
  from public.orders
  join public.sales_channels on sales_channels.id = orders.channel_id
  where orders.id = p_order_id;
$$;

create function public.add_order_consultation_note(
  p_order_id uuid,
  p_content text
)
returns jsonb
language plpgsql
security invoker
set search_path = ''
as $$
declare
  note_id bigint;
begin
  if nullif(trim(coalesce(p_content, '')), '') is null then
    raise exception '상담 메모를 입력해 주세요.' using errcode = '22023';
  end if;

  if char_length(trim(p_content)) > 2000 then
    raise exception '상담 메모는 2,000자 이하로 입력해 주세요.' using errcode = '22023';
  end if;

  if not exists (
    select 1
    from public.orders
    where orders.id = p_order_id
  ) then
    raise exception '주문을 찾을 수 없습니다.' using errcode = 'P0002';
  end if;

  insert into public.order_consultation_notes (
    order_id,
    author_id,
    content
  )
  values (
    p_order_id,
    (select auth.uid()),
    trim(p_content)
  )
  returning id into note_id;

  return (
    select jsonb_build_object(
      'id', order_consultation_notes.id,
      'content', order_consultation_notes.content,
      'authorId', order_consultation_notes.author_id,
      'authorName', profiles.display_name,
      'createdAt', order_consultation_notes.created_at
    )
    from public.order_consultation_notes
    left join public.profiles on profiles.id = order_consultation_notes.author_id
    where order_consultation_notes.id = note_id
  );
end;
$$;

revoke all on function public.update_order_detail(uuid, jsonb) from public;
grant execute on function public.update_order_detail(uuid, jsonb) to authenticated;

revoke all on function public.add_order_consultation_note(uuid, text) from public;
grant execute on function public.add_order_consultation_note(uuid, text) to authenticated;

comment on function public.update_order_detail(uuid, jsonb) is
  'Updates only the order fields allowed for its current status and returns the detail.';

comment on function public.add_order_consultation_note(uuid, text) is
  'Appends an immutable consultation note to an order.';
