-- Order detail data for the admin order detail page.

alter table public.orders
add column customer_phone text;

alter table public.order_items
add column product_sku text;

update public.orders
set customer_phone = '010-0000-' || right(order_number, 4)
where customer_phone is null;

update public.order_items
set product_sku = products.sku
from public.products
where products.id = order_items.product_id
  and order_items.product_sku is null;

create table public.order_payments (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null unique references public.orders (id) on delete cascade,
  method text not null
    check (method in ('card', 'bank_transfer', 'virtual_account', 'kakao_pay')),
  status text not null
    check (status in ('pending', 'paid', 'partially_refunded', 'refunded', 'failed', 'cancelled')),
  product_amount integer not null check (product_amount >= 0),
  discount_amount integer not null default 0 check (discount_amount >= 0),
  shipping_fee integer not null default 0 check (shipping_fee >= 0),
  paid_amount integer not null check (paid_amount >= 0),
  transaction_id text unique,
  paid_at timestamptz,
  refunded_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.order_shipments (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null unique references public.orders (id) on delete cascade,
  recipient_name text not null,
  recipient_phone text not null,
  postal_code text not null,
  address_line1 text not null,
  address_line2 text,
  delivery_memo text,
  carrier text,
  tracking_number text unique,
  shipped_at timestamptz,
  delivered_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.order_status_history (
  id bigint generated by default as identity primary key,
  order_id uuid not null references public.orders (id) on delete cascade,
  status text not null
    check (status in ('paid', 'preparing', 'shipping', 'delivered', 'cancelled')),
  note text,
  changed_at timestamptz not null default now()
);

create index order_status_history_order_changed_idx
on public.order_status_history (order_id, changed_at desc);

create trigger order_payments_set_updated_at
before update on public.order_payments
for each row execute function public.set_updated_at();

create trigger order_shipments_set_updated_at
before update on public.order_shipments
for each row execute function public.set_updated_at();

alter table public.order_payments enable row level security;
alter table public.order_shipments enable row level security;
alter table public.order_status_history enable row level security;

create policy "order_payments_select_own_or_admin"
on public.order_payments for select to authenticated
using (
  exists (
    select 1
    from public.orders
    where orders.id = order_payments.order_id
      and (orders.user_id = (select auth.uid()) or (select public.is_admin()))
  )
);

create policy "order_payments_admin_write"
on public.order_payments for all to authenticated
using ((select public.is_admin()))
with check ((select public.is_admin()));

create policy "order_shipments_select_own_or_admin"
on public.order_shipments for select to authenticated
using (
  exists (
    select 1
    from public.orders
    where orders.id = order_shipments.order_id
      and (orders.user_id = (select auth.uid()) or (select public.is_admin()))
  )
);

create policy "order_shipments_admin_write"
on public.order_shipments for all to authenticated
using ((select public.is_admin()))
with check ((select public.is_admin()));

create policy "order_status_history_select_own_or_admin"
on public.order_status_history for select to authenticated
using (
  exists (
    select 1
    from public.orders
    where orders.id = order_status_history.order_id
      and (orders.user_id = (select auth.uid()) or (select public.is_admin()))
  )
);

create policy "order_status_history_admin_write"
on public.order_status_history for all to authenticated
using ((select public.is_admin()))
with check ((select public.is_admin()));

grant select, insert, update, delete on
  public.order_payments,
  public.order_shipments,
  public.order_status_history
to authenticated;

grant usage, select on sequence public.order_status_history_id_seq
to authenticated, service_role;

insert into public.order_payments (
  order_id,
  method,
  status,
  product_amount,
  discount_amount,
  shipping_fee,
  paid_amount,
  transaction_id,
  paid_at,
  refunded_at
)
select
  orders.id,
  case mod(hashtext(orders.order_number)::bigint + 2147483648, 4)
    when 0 then 'card'
    when 1 then 'bank_transfer'
    when 2 then 'virtual_account'
    else 'kakao_pay'
  end,
  case when orders.status = 'cancelled' then 'refunded' else 'paid' end,
  orders.total_amount,
  0,
  0,
  orders.total_amount,
  'PAY-' || replace(orders.id::text, '-', ''),
  orders.ordered_at + interval '1 minute',
  case
    when orders.status = 'cancelled' then orders.ordered_at + interval '2 hours'
    else null
  end
from public.orders;

insert into public.order_shipments (
  order_id,
  recipient_name,
  recipient_phone,
  postal_code,
  address_line1,
  address_line2,
  delivery_memo,
  carrier,
  tracking_number,
  shipped_at,
  delivered_at
)
select
  orders.id,
  orders.customer_name,
  orders.customer_phone,
  lpad((6000 + mod(hashtext(orders.order_number)::bigint + 2147483648, 9000))::text, 5, '0'),
  case mod(hashtext(orders.order_number)::bigint + 2147483648, 4)
    when 0 then '서울특별시 성동구 왕십리로 125'
    when 1 then '경기도 성남시 분당구 판교역로 166'
    when 2 then '부산광역시 해운대구 센텀중앙로 97'
    else '대전광역시 유성구 대학로 99'
  end,
  right(orders.order_number, 4) || '호',
  case mod(hashtext(orders.order_number)::bigint + 2147483648, 3)
    when 0 then '문 앞에 놓아주세요.'
    when 1 then '배송 전에 연락 부탁드립니다.'
    else '경비실에 맡겨주세요.'
  end,
  case when orders.status in ('shipping', 'delivered') then 'CJ대한통운' else null end,
  case
    when orders.status in ('shipping', 'delivered')
      then 'TRACK-' || right(replace(orders.id::text, '-', ''), 12)
    else null
  end,
  case
    when orders.status in ('shipping', 'delivered')
      then orders.ordered_at + interval '1 day'
    else null
  end,
  case
    when orders.status = 'delivered' then orders.ordered_at + interval '2 days'
    else null
  end
from public.orders;

insert into public.order_status_history (order_id, status, note, changed_at)
select id, 'paid', '결제가 완료되었습니다.', ordered_at + interval '1 minute'
from public.orders;

insert into public.order_status_history (order_id, status, note, changed_at)
select id, 'preparing', '상품 준비가 시작되었습니다.', ordered_at + interval '4 hours'
from public.orders
where status in ('preparing', 'shipping', 'delivered');

insert into public.order_status_history (order_id, status, note, changed_at)
select id, 'shipping', '배송이 시작되었습니다.', ordered_at + interval '1 day'
from public.orders
where status in ('shipping', 'delivered');

insert into public.order_status_history (order_id, status, note, changed_at)
select id, 'delivered', '배송이 완료되었습니다.', ordered_at + interval '2 days'
from public.orders
where status = 'delivered';

insert into public.order_status_history (order_id, status, note, changed_at)
select id, 'cancelled', '주문이 취소되고 결제 금액이 환불되었습니다.', ordered_at + interval '2 hours'
from public.orders
where status = 'cancelled';

create function public.get_order_detail(p_order_id uuid)
returns jsonb
language sql
stable
security invoker
set search_path = ''
as $$
  select jsonb_build_object(
    'id', orders.id,
    'orderNumber', orders.order_number,
    'status', orders.status,
    'orderedAt', orders.ordered_at,
    'updatedAt', orders.updated_at,
    'totalAmount', orders.total_amount,
    'salesChannel', sales_channels.name,
    'customer', jsonb_build_object(
      'name', orders.customer_name,
      'email', orders.customer_email,
      'phone', orders.customer_phone
    ),
    'items', (
      select coalesce(
        jsonb_agg(
          jsonb_build_object(
            'id', order_items.id,
            'productId', order_items.product_id,
            'sku', order_items.product_sku,
            'name', order_items.product_name,
            'quantity', order_items.quantity,
            'unitPrice', order_items.unit_price,
            'totalAmount', order_items.unit_price * order_items.quantity
          )
          order by order_items.id
        ),
        '[]'::jsonb
      )
      from public.order_items
      where order_items.order_id = orders.id
    ),
    'payment', (
      select jsonb_build_object(
        'method', order_payments.method,
        'status', order_payments.status,
        'productAmount', order_payments.product_amount,
        'discountAmount', order_payments.discount_amount,
        'shippingFee', order_payments.shipping_fee,
        'paidAmount', order_payments.paid_amount,
        'transactionId', order_payments.transaction_id,
        'paidAt', order_payments.paid_at,
        'refundedAt', order_payments.refunded_at
      )
      from public.order_payments
      where order_payments.order_id = orders.id
    ),
    'shipping', (
      select jsonb_build_object(
        'recipientName', order_shipments.recipient_name,
        'recipientPhone', order_shipments.recipient_phone,
        'postalCode', order_shipments.postal_code,
        'addressLine1', order_shipments.address_line1,
        'addressLine2', order_shipments.address_line2,
        'deliveryMemo', order_shipments.delivery_memo,
        'carrier', order_shipments.carrier,
        'trackingNumber', order_shipments.tracking_number,
        'shippedAt', order_shipments.shipped_at,
        'deliveredAt', order_shipments.delivered_at
      )
      from public.order_shipments
      where order_shipments.order_id = orders.id
    ),
    'statusHistory', (
      select coalesce(
        jsonb_agg(
          jsonb_build_object(
            'id', order_status_history.id,
            'status', order_status_history.status,
            'note', order_status_history.note,
            'changedAt', order_status_history.changed_at
          )
          order by order_status_history.changed_at desc
        ),
        '[]'::jsonb
      )
      from public.order_status_history
      where order_status_history.order_id = orders.id
    )
  )
  from public.orders
  join public.sales_channels on sales_channels.id = orders.channel_id
  where orders.id = p_order_id;
$$;

revoke all on function public.get_order_detail(uuid) from public;
grant execute on function public.get_order_detail(uuid) to authenticated;

comment on function public.get_order_detail(uuid) is
  'Returns one order with customer, item, payment, shipping, and status history data.';
