create table public.admin_navigation_menus (
  id bigint generated by default as identity primary key,
  code text not null unique,
  label text not null,
  href text not null,
  icon text not null
    check (icon in ('dashboard', 'orders', 'inventory', 'customers', 'reports', 'settings')),
  section text not null default 'main'
    check (section in ('main', 'footer')),
  sort_order integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create trigger admin_navigation_menus_set_updated_at
before update on public.admin_navigation_menus
for each row execute function public.set_updated_at();

alter table public.admin_navigation_menus enable row level security;

create policy "admin_navigation_menus_authenticated_read"
on public.admin_navigation_menus for select to authenticated
using (true);

create policy "admin_navigation_menus_admin_write"
on public.admin_navigation_menus for all to authenticated
using ((select public.is_admin()))
with check ((select public.is_admin()));

grant select on public.admin_navigation_menus to authenticated;
grant insert, update, delete on public.admin_navigation_menus to authenticated;
grant usage, select on sequence public.admin_navigation_menus_id_seq
to authenticated, service_role;

insert into public.admin_navigation_menus (
  code,
  label,
  href,
  icon,
  section,
  sort_order
)
values
  ('dashboard', '대시보드', '/', 'dashboard', 'main', 10),
  ('orders', '주문 관리', '/order', 'orders', 'main', 20),
  ('inventory', '재고 관리', '/inventory', 'inventory', 'main', 30),
  ('customers', '고객 관리', '/customers', 'customers', 'main', 40),
  ('reports', '리포트', '/reports', 'reports', 'main', 50),
  ('settings', '설정', '/settings', 'settings', 'footer', 10);

create or replace function public.get_admin_navigation()
returns jsonb
language sql
stable
security invoker
set search_path = ''
as $$
  select coalesce(
    jsonb_agg(
      jsonb_build_object(
        'code', menus.code,
        'label', menus.label,
        'href', menus.href,
        'icon', menus.icon,
        'section', menus.section
      )
      order by menus.section, menus.sort_order, menus.id
    ),
    '[]'::jsonb
  )
  from public.admin_navigation_menus as menus
  where menus.is_active = true;
$$;

revoke all on function public.get_admin_navigation() from public;
grant execute on function public.get_admin_navigation() to authenticated;

comment on table public.admin_navigation_menus is
  'Configurable sidebar navigation for the admin application.';
