-- FlowOps database schema
-- Authentication and sessions are managed by Supabase Auth (`auth` schema).

create table public.profiles (
  id uuid primary key references auth.users (id) on delete cascade,
  display_name text,
  avatar_url text,
  role text not null default 'customer'
    check (role in ('customer', 'admin')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.sales_channels (
  id bigint generated by default as identity primary key,
  code text not null unique,
  name text not null unique,
  created_at timestamptz not null default now()
);

create table public.products (
  id uuid primary key default gen_random_uuid(),
  sku text not null unique,
  name text not null,
  description text,
  price integer not null check (price >= 0),
  status text not null default 'active'
    check (status in ('active', 'inactive')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.inventory (
  product_id uuid primary key references public.products (id) on delete cascade,
  on_hand integer not null default 0 check (on_hand >= 0),
  reserved integer not null default 0 check (reserved >= 0),
  reorder_point integer not null default 10 check (reorder_point >= 0),
  available integer generated always as (on_hand - reserved) stored,
  updated_at timestamptz not null default now(),
  check (reserved <= on_hand)
);

create table public.orders (
  id uuid primary key default gen_random_uuid(),
  order_number text not null unique,
  user_id uuid references auth.users (id) on delete set null,
  channel_id bigint not null references public.sales_channels (id),
  customer_name text not null,
  customer_email text,
  status text not null
    check (status in ('paid', 'preparing', 'shipping', 'delivered', 'cancelled')),
  total_amount integer not null check (total_amount >= 0),
  ordered_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.order_items (
  id bigint generated by default as identity primary key,
  order_id uuid not null references public.orders (id) on delete cascade,
  product_id uuid references public.products (id) on delete set null,
  product_name text not null,
  quantity integer not null check (quantity > 0),
  unit_price integer not null check (unit_price >= 0),
  created_at timestamptz not null default now(),
  unique (order_id, product_id)
);

-- Imported channel aggregates power the dashboard without fabricating hundreds
-- of detailed orders in the demo database.
create table public.daily_channel_metrics (
  stat_date date not null,
  channel_id bigint not null references public.sales_channels (id) on delete cascade,
  order_count integer not null check (order_count >= 0),
  gross_revenue bigint not null check (gross_revenue >= 0),
  primary key (stat_date, channel_id)
);

create index orders_ordered_at_idx on public.orders (ordered_at desc);
create index orders_user_id_idx on public.orders (user_id);
create index orders_status_idx on public.orders (status);
create index order_items_order_id_idx on public.order_items (order_id);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger profiles_set_updated_at
before update on public.profiles
for each row execute function public.set_updated_at();

create trigger products_set_updated_at
before update on public.products
for each row execute function public.set_updated_at();

create trigger inventory_set_updated_at
before update on public.inventory
for each row execute function public.set_updated_at();

create trigger orders_set_updated_at
before update on public.orders
for each row execute function public.set_updated_at();

-- A public profile is created for email OTP and Kakao users alike.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.profiles (id, display_name, avatar_url)
  values (
    new.id,
    coalesce(
      new.raw_user_meta_data ->> 'full_name',
      new.raw_user_meta_data ->> 'name',
      split_part(coalesce(new.email, ''), '@', 1)
    ),
    coalesce(
      new.raw_user_meta_data ->> 'avatar_url',
      new.raw_user_meta_data ->> 'picture'
    )
  );
  return new;
end;
$$;

create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_user();

-- Used only inside RLS policies. Users cannot promote themselves to admin.
create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.profiles
    where id = (select auth.uid())
      and role = 'admin'
  );
$$;

revoke all on function public.is_admin() from public;
grant execute on function public.is_admin() to authenticated;

alter table public.profiles enable row level security;
alter table public.sales_channels enable row level security;
alter table public.products enable row level security;
alter table public.inventory enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;
alter table public.daily_channel_metrics enable row level security;

create policy "profiles_select_self_or_admin"
on public.profiles for select to authenticated
using ((select auth.uid()) = id or (select public.is_admin()));

create policy "profiles_update_self"
on public.profiles for update to authenticated
using ((select auth.uid()) = id)
with check ((select auth.uid()) = id);

create policy "channels_public_read"
on public.sales_channels for select to anon, authenticated
using (true);

create policy "channels_admin_write"
on public.sales_channels for all to authenticated
using ((select public.is_admin()))
with check ((select public.is_admin()));

create policy "products_public_read_active"
on public.products for select to anon, authenticated
using (status = 'active');

create policy "products_admin_read_all"
on public.products for select to authenticated
using ((select public.is_admin()));

create policy "products_admin_write"
on public.products for all to authenticated
using ((select public.is_admin()))
with check ((select public.is_admin()));

create policy "inventory_admin_all"
on public.inventory for all to authenticated
using ((select public.is_admin()))
with check ((select public.is_admin()));

create policy "orders_select_own_or_admin"
on public.orders for select to authenticated
using (user_id = (select auth.uid()) or (select public.is_admin()));

create policy "orders_admin_write"
on public.orders for all to authenticated
using ((select public.is_admin()))
with check ((select public.is_admin()));

create policy "order_items_select_own_or_admin"
on public.order_items for select to authenticated
using (
  exists (
    select 1
    from public.orders
    where orders.id = order_items.order_id
      and (orders.user_id = (select auth.uid()) or (select public.is_admin()))
  )
);

create policy "order_items_admin_write"
on public.order_items for all to authenticated
using ((select public.is_admin()))
with check ((select public.is_admin()));

create policy "daily_metrics_admin_all"
on public.daily_channel_metrics for all to authenticated
using ((select public.is_admin()))
with check ((select public.is_admin()));

revoke all on public.profiles from anon, authenticated;
grant select on public.profiles to authenticated;
grant update (display_name, avatar_url) on public.profiles to authenticated;

grant select on public.sales_channels, public.products to anon, authenticated;
grant insert, update, delete on public.sales_channels, public.products to authenticated;
grant select, insert, update, delete on
  public.inventory,
  public.orders,
  public.order_items,
  public.daily_channel_metrics
to authenticated;

grant all on all tables in schema public to service_role;
grant usage, select on all sequences in schema public to authenticated, service_role;

create view public.dashboard_weekly_sales
with (security_invoker = true)
as
select
  stat_date,
  sum(order_count)::integer as order_count,
  sum(gross_revenue)::bigint as gross_revenue
from public.daily_channel_metrics
group by stat_date;

create view public.dashboard_channel_share
with (security_invoker = true)
as
with latest as (
  select max(stat_date) as max_date
  from public.daily_channel_metrics
)
select
  channels.code,
  channels.name,
  sum(metrics.order_count)::integer as order_count,
  round(
    100.0 * sum(metrics.order_count)
      / nullif(sum(sum(metrics.order_count)) over (), 0),
    1
  ) as share_percent
from public.daily_channel_metrics as metrics
join public.sales_channels as channels on channels.id = metrics.channel_id
cross join latest
where metrics.stat_date > latest.max_date - 7
group by channels.code, channels.name;

grant select on public.dashboard_weekly_sales, public.dashboard_channel_share
to authenticated, service_role;

comment on table public.profiles is 'Application profile linked to Supabase Auth users.';
comment on column public.profiles.role is 'Authorization role; update only from a trusted server or SQL editor.';
comment on table public.daily_channel_metrics is 'Daily channel aggregates used by the operations dashboard.';
